// THIS FILE IS AUTOGENERATED. EDIT THE .json INSTEAD

#ifndef ALPHA_STAGE_V2_SCENE_DEFS_H
#define ALPHA_STAGE_V2_SCENE_DEFS_H

#include "scene_colors_generator.h"
#include "stage_section.h"
#include "static_model_3d_item.h"
#include "enemy_def.h"
#include "bn_color.h"
#include "bn_span.h"
#include "colliders.h"
#include "player_laser.h"
#include "player_ship.h"
#include "enemies/asteroid.h"
#include "enemies/oyster.h"
#include "enemies/scorpion.h"
#include "models/big_asteroid_1.h"
#include "models/player_ship_02.h"
#include "models/shot.h"

using namespace scene_colors_generator;

// --- Sections


constexpr std::initializer_list<fr::model_3d_item> _section_1_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_1_enemies = {
    enemy_def{fr::point_3d(20, 200, -20), 800, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_1_start = 1050;
constexpr int _section_1_end = 250;
constexpr bool _section_1_end_section = false;

constexpr stage_section section_1(_section_1_start, _section_1_end,
                                  _section_1_static_model_items, _section_1_enemies,
                                  _section_1_end_section);


constexpr std::initializer_list<fr::model_3d_item> _section_2_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_2_enemies = {
    enemy_def{fr::point_3d(-50, 0, 30), 200, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_2_start = 750;
constexpr int _section_2_end = -150;
constexpr bool _section_2_end_section = false;

constexpr stage_section section_2(_section_2_start, _section_2_end,
                                  _section_2_static_model_items, _section_2_enemies,
                                  _section_2_end_section);


constexpr std::initializer_list<fr::model_3d_item> _section_3_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_3_enemies = {
    enemy_def{fr::point_3d(-20, -430, 20), 100, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(20, -415, 15), 300, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(60, -400, 10), 500, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_3_start = 450;
constexpr int _section_3_end = -350;
constexpr bool _section_3_end_section = false;

constexpr stage_section section_3(_section_3_start, _section_3_end,
                                  _section_3_static_model_items, _section_3_enemies,
                                  _section_3_end_section);


constexpr std::initializer_list<fr::model_3d_item> _section_4_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_4_enemies = {
    enemy_def{fr::point_3d(0, -830, -20), 100, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(-40, -815, -15), 300, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(-80, -800, -10), 500, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_4_start = 50;
constexpr int _section_4_end = -750;
constexpr bool _section_4_end_section = false;

constexpr stage_section section_4(_section_4_start, _section_4_end,
                                  _section_4_static_model_items, _section_4_enemies,
                                  _section_4_end_section);


constexpr oyster_properties _s5_enemy_1_props = {300};

constexpr std::initializer_list<fr::model_3d_item> _section_5_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_5_enemies = {
    enemy_def{fr::point_3d(-50, -1250, -30), 100, enemy_type::OYSTER, &_s5_enemy_1_props}
};

constexpr int _section_5_start = -450;
constexpr int _section_5_end = -2350;
constexpr bool _section_5_end_section = false;

constexpr stage_section section_5(_section_5_start, _section_5_end,
                                  _section_5_static_model_items, _section_5_enemies,
                                  _section_5_end_section);


constexpr oyster_properties _s6_enemy_1_props = {320};

constexpr std::initializer_list<fr::model_3d_item> _section_6_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_6_enemies = {
    enemy_def{fr::point_3d(50, -1750, 30), 300, enemy_type::OYSTER, &_s6_enemy_1_props}
};

constexpr int _section_6_start = -950;
constexpr int _section_6_end = -2850;
constexpr bool _section_6_end_section = false;

constexpr stage_section section_6(_section_6_start, _section_6_end,
                                  _section_6_static_model_items, _section_6_enemies,
                                  _section_6_end_section);


constexpr asteroid_properties _s7_enemy_2_props = {1};

constexpr std::initializer_list<fr::model_3d_item> _section_7_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_7_enemies = {
    enemy_def{fr::point_3d(0, -2250, -20), 100, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(-80, -2450, 30), 500, enemy_type::ASTEROID, &_s7_enemy_2_props}
};

constexpr int _section_7_start = -1450;
constexpr int _section_7_end = -2350;
constexpr bool _section_7_end_section = false;

constexpr stage_section section_7(_section_7_start, _section_7_end,
                                  _section_7_static_model_items, _section_7_enemies,
                                  _section_7_end_section);


constexpr asteroid_properties _s8_enemy_1_props = {2};

constexpr std::initializer_list<fr::model_3d_item> _section_8_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_8_enemies = {
    enemy_def{fr::point_3d(-40, -2550, -35), 300, enemy_type::ASTEROID, &_s8_enemy_1_props}
};

constexpr int _section_8_start = -1650;
constexpr int _section_8_end = -2550;
constexpr bool _section_8_end_section = false;

constexpr stage_section section_8(_section_8_start, _section_8_end,
                                  _section_8_static_model_items, _section_8_enemies,
                                  _section_8_end_section);


constexpr asteroid_properties _s9_enemy_1_props = {3};

constexpr std::initializer_list<fr::model_3d_item> _section_9_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_9_enemies = {
    enemy_def{fr::point_3d(50, -2750, -10), 100, enemy_type::ASTEROID, &_s9_enemy_1_props},
    enemy_def{fr::point_3d(-50, -2650, 30), 500, enemy_type::SCORPION, nullptr}
};

constexpr int _section_9_start = -1850;
constexpr int _section_9_end = -2850;
constexpr bool _section_9_end_section = false;

constexpr stage_section section_9(_section_9_start, _section_9_end,
                                  _section_9_static_model_items, _section_9_enemies,
                                  _section_9_end_section);

constexpr auto _s10_model_1 =
    static_model_3d_item<fr::model_3d_items::big_asteroid_1_full>(
        fr::point_3d(-40, -3100, -30), 16000, fr::model_3d_items::asteroid_alt1_colors);

constexpr std::initializer_list<fr::model_3d_item> _section_10_static_model_items = {
    _s10_model_1.item()
};

constexpr std::initializer_list<enemy_def> _section_10_enemies = {};

constexpr sphere_collider _section_10_static_colliders[] = {
    sphere_collider(fr::point_3d(-50, -3100, -30), 40)
};
constexpr int _section_10_static_colliders_count =
    sizeof(_section_10_static_colliders) / sizeof(_section_10_static_colliders[0]);

constexpr int _section_10_start = -2350;
constexpr int _section_10_end = -3550;
constexpr bool _section_10_end_section = false;

constexpr stage_section section_10(_section_10_start, _section_10_end,
                                  _section_10_static_model_items, _section_10_enemies,
                                  _section_10_static_colliders, _section_10_static_colliders_count,
                                  _section_10_end_section);

constexpr auto _s11_model_1 =
    static_model_3d_item<fr::model_3d_items::big_asteroid_1_full>(
        fr::point_3d(40, -3550, 40), -8000, fr::model_3d_items::asteroid_alt1_colors);

constexpr asteroid_properties _s11_enemy_1_props = {3};

constexpr std::initializer_list<fr::model_3d_item> _section_11_static_model_items = {
    _s11_model_1.item()
};

constexpr std::initializer_list<enemy_def> _section_11_enemies = {
    enemy_def{fr::point_3d(50, -3600, -35), 100, enemy_type::ASTEROID, &_s11_enemy_1_props}
};

constexpr sphere_collider _section_11_static_colliders[] = {
    sphere_collider(fr::point_3d(50, -3550, 40), 40)
};
constexpr int _section_11_static_colliders_count =
    sizeof(_section_11_static_colliders) / sizeof(_section_11_static_colliders[0]);

constexpr int _section_11_start = -2650;
constexpr int _section_11_end = -3950;
constexpr bool _section_11_end_section = false;

constexpr stage_section section_11(_section_11_start, _section_11_end,
                                  _section_11_static_model_items, _section_11_enemies,
                                  _section_11_static_colliders, _section_11_static_colliders_count,
                                  _section_11_end_section);


constexpr asteroid_properties _s12_enemy_1_props = {2};

constexpr std::initializer_list<fr::model_3d_item> _section_12_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_12_enemies = {
    enemy_def{fr::point_3d(-50, -3930, -30), 100, enemy_type::ASTEROID, &_s12_enemy_1_props}
};

constexpr int _section_12_start = -2950;
constexpr int _section_12_end = -3850;
constexpr bool _section_12_end_section = false;

constexpr stage_section section_12(_section_12_start, _section_12_end,
                                  _section_12_static_model_items, _section_12_enemies,
                                  _section_12_end_section);


constexpr asteroid_properties _s13_enemy_1_props = {5};

constexpr std::initializer_list<fr::model_3d_item> _section_13_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_13_enemies = {
    enemy_def{fr::point_3d(60, -4050, -35), 100, enemy_type::ASTEROID, &_s13_enemy_1_props}
};

constexpr int _section_13_start = -3150;
constexpr int _section_13_end = -4050;
constexpr bool _section_13_end_section = false;

constexpr stage_section section_13(_section_13_start, _section_13_end,
                                  _section_13_static_model_items, _section_13_enemies,
                                  _section_13_end_section);


constexpr oyster_properties _s14_enemy_1_props = {320};

constexpr std::initializer_list<fr::model_3d_item> _section_14_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_14_enemies = {
    enemy_def{fr::point_3d(-20, -4350, 40), 100, enemy_type::OYSTER, &_s14_enemy_1_props}
};

constexpr int _section_14_start = -3550;
constexpr int _section_14_end = -4600;
constexpr bool _section_14_end_section = false;

constexpr stage_section section_14(_section_14_start, _section_14_end,
                                  _section_14_static_model_items, _section_14_enemies,
                                  _section_14_end_section);


constexpr oyster_properties _s15_enemy_1_props = {250};
constexpr oyster_properties _s15_enemy_2_props = {300};

constexpr std::initializer_list<fr::model_3d_item> _section_15_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_15_enemies = {
    enemy_def{fr::point_3d(70, -4450, 10), 100, enemy_type::OYSTER, &_s15_enemy_1_props},
    enemy_def{fr::point_3d(-60, -4650, -40), 300, enemy_type::OYSTER, &_s15_enemy_2_props}
};

constexpr int _section_15_start = -3750;
constexpr int _section_15_end = -4850;
constexpr bool _section_15_end_section = false;

constexpr stage_section section_15(_section_15_start, _section_15_end,
                                  _section_15_static_model_items, _section_15_enemies,
                                  _section_15_end_section);

constexpr auto _s16_model_1 =
    static_model_3d_item<fr::model_3d_items::big_asteroid_1_full>(
        fr::point_3d(45, -5500, -45), 18000, fr::model_3d_items::asteroid_alt1_colors);

constexpr std::initializer_list<fr::model_3d_item> _section_16_static_model_items = {
    _s16_model_1.item()
};

constexpr std::initializer_list<enemy_def> _section_16_enemies = {};

constexpr sphere_collider _section_16_static_colliders[] = {
    sphere_collider(fr::point_3d(55, -5500, -45), 40)
};
constexpr int _section_16_static_colliders_count =
    sizeof(_section_16_static_colliders) / sizeof(_section_16_static_colliders[0]);

constexpr int _section_16_start = -4550;
constexpr int _section_16_end = -5600;
constexpr bool _section_16_end_section = false;

constexpr stage_section section_16(_section_16_start, _section_16_end,
                                  _section_16_static_model_items, _section_16_enemies,
                                  _section_16_static_colliders, _section_16_static_colliders_count,
                                  _section_16_end_section);


constexpr std::initializer_list<fr::model_3d_item> _section_17_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_17_enemies = {
    enemy_def{fr::point_3d(-70, -5650, 50), 100, enemy_type::SCORPION, nullptr}
};

constexpr int _section_17_start = -4750;
constexpr int _section_17_end = -5900;
constexpr bool _section_17_end_section = false;

constexpr stage_section section_17(_section_17_start, _section_17_end,
                                  _section_17_static_model_items, _section_17_enemies,
                                  _section_17_end_section);


constexpr asteroid_properties _s18_enemy_1_props = {5};

constexpr std::initializer_list<fr::model_3d_item> _section_18_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_18_enemies = {
    enemy_def{fr::point_3d(60, -5830, 40), 100, enemy_type::ASTEROID, &_s18_enemy_1_props}
};

constexpr int _section_18_start = -4850;
constexpr int _section_18_end = -6000;
constexpr bool _section_18_end_section = false;

constexpr stage_section section_18(_section_18_start, _section_18_end,
                                  _section_18_static_model_items, _section_18_enemies,
                                  _section_18_end_section);


constexpr oyster_properties _s19_enemy_1_props = {320};

constexpr std::initializer_list<fr::model_3d_item> _section_19_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_19_enemies = {
    enemy_def{fr::point_3d(20, -6330, -30), 100, enemy_type::OYSTER, &_s19_enemy_1_props},
    enemy_def{fr::point_3d(-60, -6250, 0), 100, enemy_type::SCORPION, nullptr}
};

constexpr int _section_19_start = -5350;
constexpr int _section_19_end = -6500;
constexpr bool _section_19_end_section = false;

constexpr stage_section section_19(_section_19_start, _section_19_end,
                                  _section_19_static_model_items, _section_19_enemies,
                                  _section_19_end_section);


constexpr oyster_properties _s20_enemy_1_props = {350};

constexpr std::initializer_list<fr::model_3d_item> _section_20_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_20_enemies = {
    enemy_def{fr::point_3d(-40, -6650, -60), 100, enemy_type::OYSTER, &_s20_enemy_1_props}
};

constexpr int _section_20_start = -5750;
constexpr int _section_20_end = -6900;
constexpr bool _section_20_end_section = false;

constexpr stage_section section_20(_section_20_start, _section_20_end,
                                  _section_20_static_model_items, _section_20_enemies,
                                  _section_20_end_section);


constexpr asteroid_properties _s21_enemy_2_props = {3};
constexpr asteroid_properties _s21_enemy_3_props = {2};

constexpr std::initializer_list<fr::model_3d_item> _section_21_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_21_enemies = {
    enemy_def{fr::point_3d(60, -7250, 60), 100, enemy_type::SCORPION, nullptr},
    enemy_def{fr::point_3d(-60, -7250, 50), 100, enemy_type::ASTEROID, &_s21_enemy_2_props},
    enemy_def{fr::point_3d(-20, -7250, 20), 100, enemy_type::ASTEROID, &_s21_enemy_3_props}
};

constexpr int _section_21_start = -6350;
constexpr int _section_21_end = -7300;
constexpr bool _section_21_end_section = true;

constexpr stage_section section_21(_section_21_start, _section_21_end,
                                  _section_21_static_model_items, _section_21_enemies,
                                  _section_21_end_section);

// # Sections List

constexpr const auto sections_full = {
    &section_1,
    &section_2,
    &section_3,
    &section_4,
    &section_5,
    &section_6,
    &section_7,
    &section_8,
    &section_9,
    &section_10,
    &section_11,
    &section_12,
    &section_13,
    &section_14,
    &section_15,
    &section_16,
    &section_17,
    &section_18,
    &section_19,
    &section_20,
    &section_21,
};

constexpr stage_section_list_ptr sections = sections_full.begin();
constexpr size_t sections_count = sections_full.size();

// --- Colors

constexpr const auto raw_scene_colors = {
    bn::span<const bn::color>(fr::model_3d_items::debug_collider_colors),
    bn::span<const bn::color>(fr::model_3d_items::laser_colors),
    bn::span<const bn::color>(fr::model_3d_items::hurt_colors),
    bn::span<const bn::color>(fr::model_3d_items::player_ship_02_colors),
    bn::span<const bn::color>(fr::model_3d_items::asteroid_alt1_colors),
    bn::span<const bn::color>(fr::model_3d_items::oyster_alt1_colors),
    bn::span<const bn::color>(fr::model_3d_items::scorpion_alt_colors),
    bn::span<const bn::color>(fr::model_3d_items::shot_colors)
};

constexpr size_t model_palette_count = raw_scene_colors.size();
constexpr size_t scene_palette_size = calculate_total_size(raw_scene_colors);
constexpr const bn::span<const bn::color> *raw_scene_color_ptr = raw_scene_colors.begin();

constexpr bn::array<bn::color, scene_palette_size> scene_colors = generate_scene_colors<scene_palette_size>(raw_scene_colors);

inline color_mapping_handler *get_scene_color_mapping()
{
    return new color_mapping_handler(model_palette_count, scene_palette_size,
                                     raw_scene_color_ptr, scene_colors.data());
};

#endif
