// THIS FILE IS AUTOGENERATED. EDIT THE .json INSTEAD

#ifndef STAGE_1_SCENE_DEFS_H
#define STAGE_1_SCENE_DEFS_H

#include "scene_colors_generator.h"
#include "stage_section.h"
#include "static_model_3d_item.h"
#include "bn_color.h"
#include "bn_span.h"
#include "colliders.h"
#include "player_laser.h"
#include "player_ship.h"
#include "models/asteroid1.h"
#include "models/moon_oyster.h"
#include "models/player_ship_02.h"

using namespace scene_colors_generator;

// --- Sections


constexpr std::initializer_list<fr::model_3d_item> _section_1_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_1_enemies = {
    enemy_def{fr::point_3d(20, 200, -20), 800, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_1_start = 1050;
constexpr int _section_1_end = 250;

constexpr stage_section section_1(_section_1_start, _section_1_end,
                                  _section_1_static_model_items, _section_1_enemies);


constexpr std::initializer_list<fr::model_3d_item> _section_2_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_2_enemies = {
    enemy_def{fr::point_3d(-50, 0, 30), 200, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_2_start = 750;
constexpr int _section_2_end = -150;

constexpr stage_section section_2(_section_2_start, _section_2_end,
                                  _section_2_static_model_items, _section_2_enemies);


constexpr std::initializer_list<fr::model_3d_item> _section_3_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_3_enemies = {
    enemy_def{fr::point_3d(-20, -430, 20), 100, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(20, -415, 15), 300, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(60, -400, 10), 500, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_3_start = 450;
constexpr int _section_3_end = -350;

constexpr stage_section section_3(_section_3_start, _section_3_end,
                                  _section_3_static_model_items, _section_3_enemies);


constexpr std::initializer_list<fr::model_3d_item> _section_4_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_4_enemies = {
    enemy_def{fr::point_3d(0, -830, -20), 100, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(-40, -815, -15), 300, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(-80, -800, -10), 500, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_4_start = 50;
constexpr int _section_4_end = -750;

constexpr stage_section section_4(_section_4_start, _section_4_end,
                                  _section_4_static_model_items, _section_4_enemies);


constexpr std::initializer_list<fr::model_3d_item> _section_5_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_5_enemies = {
    enemy_def{fr::point_3d(0, -1150, -10), 100, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(40, -1250, -35), 300, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(-80, -1350, 30), 500, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_5_start = -350;
constexpr int _section_5_end = -1250;

constexpr stage_section section_5(_section_5_start, _section_5_end,
                                  _section_5_static_model_items, _section_5_enemies);


constexpr std::initializer_list<fr::model_3d_item> _section_6_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_6_enemies = {
    enemy_def{fr::point_3d(-40, -1350, -5), 100, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(-40, -1450, -35), 300, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(70, -1550, -25), 500, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_6_start = -550;
constexpr int _section_6_end = -1450;

constexpr stage_section section_6(_section_6_start, _section_6_end,
                                  _section_6_static_model_items, _section_6_enemies);


constexpr std::initializer_list<fr::model_3d_item> _section_7_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_7_enemies = {
    enemy_def{fr::point_3d(0, -1650, -10), 100, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(40, -1750, -35), 300, enemy_type::ASTEROID, nullptr},
    enemy_def{fr::point_3d(80, -1850, 30), 500, enemy_type::ASTEROID, nullptr}
};

constexpr int _section_7_start = -850;
constexpr int _section_7_end = -1750;

constexpr stage_section section_7(_section_7_start, _section_7_end,
                                  _section_7_static_model_items, _section_7_enemies);


constexpr oyster_properties _s8_enemy_1_props = {-500};

constexpr std::initializer_list<fr::model_3d_item> _section_8_static_model_items = {};

constexpr std::initializer_list<enemy_def> _section_8_enemies = {
    enemy_def{fr::point_3d(0, -1950, -30), 100, enemy_type::OYSTER, &_s8_enemy_1_props}
};

constexpr int _section_8_start = -1150;
constexpr int _section_8_end = -2050;

constexpr stage_section section_8(_section_8_start, _section_8_end,
                                  _section_8_static_model_items, _section_8_enemies);

// # Sections List

constexpr const auto sections_full = {
    &section_1,
    &section_2,
    &section_3,
    &section_4,
    &section_5,
    &section_6,
    &section_7,
    &section_8,
};

constexpr stage_section_list_ptr sections = sections_full.begin();
constexpr size_t sections_count = sections_full.size();

// --- Colors

constexpr const auto raw_scene_colors = {
    bn::span<const bn::color>(fr::model_3d_items::debug_collider_colors),
    bn::span<const bn::color>(fr::model_3d_items::laser_colors),
    bn::span<const bn::color>(fr::model_3d_items::hurt_colors),
    bn::span<const bn::color>(fr::model_3d_items::player_ship_02_colors),
    bn::span<const bn::color>(fr::model_3d_items::asteroid1_colors),
    bn::span<const bn::color>(fr::model_3d_items::moon_oyster_colors)
};

constexpr size_t model_palette_count = raw_scene_colors.size();
constexpr size_t scene_palette_size = calculate_total_size(raw_scene_colors);
constexpr const bn::span<const bn::color> *raw_scene_color_ptr = raw_scene_colors.begin();

constexpr bn::array<bn::color, scene_palette_size> scene_colors = generate_scene_colors<scene_palette_size>(raw_scene_colors);

inline color_mapping_handler *get_scene_color_mapping()
{
    return new color_mapping_handler(model_palette_count, scene_palette_size,
                                     raw_scene_color_ptr, scene_colors.data());
};

#endif
