#ifndef AUDIO_VIEWER_SCENE_DEFS_H
#define AUDIO_VIEWER_SCENE_DEFS_H

// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate_audio_viewer_defs.py
// Sound files included: 10

#include "audio_viewer_scene.h"
#include "bn_sound_item.h"

#include "bn_sound_items.h"

namespace audio_viewer_defs {
inline constexpr int sound_count = 10;
inline const audio_viewer_scene::sound_entry entries[sound_count] = {
    { bn::sound_items::dodge, "Dodge" },
    { bn::sound_items::enemy_death, "Enemy Death" },
    { bn::sound_items::impact, "Impact" },
    { bn::sound_items::mc_test_04, "Mc Test 04" },
    { bn::sound_items::mc_test_05, "Mc Test 05" },
    { bn::sound_items::menu_confirm, "Menu Confirm" },
    { bn::sound_items::menu_focus, "Menu Focus" },
    { bn::sound_items::player_damage, "Player Damage" },
    { bn::sound_items::player_death, "Player Death" },
    { bn::sound_items::player_laser, "Player Laser" },
};
} // namespace audio_viewer_defs

#endif // AUDIO_VIEWER_SCENE_DEFS_H
