#ifndef AUDIO_VIEWER_SCENE_DEFS_H
#define AUDIO_VIEWER_SCENE_DEFS_H

// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate_audio_viewer_defs.py
// Sound files included: 33

#include "audio_viewer_scene.h"
#include "bn_sound_item.h"

#include "bn_sound_items.h"

namespace audio_viewer_defs {
inline constexpr int sound_count = 33;
inline const audio_viewer_scene::sound_entry entries[sound_count] = {
    { bn::sound_items::dodge, "Dodge" },
    { bn::sound_items::enemy_death, "Enemy Death" },
    { bn::sound_items::impact, "Impact" },
    { bn::sound_items::mc_1_1_1, "Mc 1 1 1" },
    { bn::sound_items::mc_1_1_2, "Mc 1 1 2" },
    { bn::sound_items::mc_1_1_3, "Mc 1 1 3" },
    { bn::sound_items::mc_1_1_4, "Mc 1 1 4" },
    { bn::sound_items::mc_1_1_5, "Mc 1 1 5" },
    { bn::sound_items::mc_1_1_6, "Mc 1 1 6" },
    { bn::sound_items::mc_1_1_7, "Mc 1 1 7" },
    { bn::sound_items::mc_1_1_8, "Mc 1 1 8" },
    { bn::sound_items::mc_2_1_1, "Mc 2 1 1" },
    { bn::sound_items::mc_2_1_2, "Mc 2 1 2" },
    { bn::sound_items::mc_2_1_3, "Mc 2 1 3" },
    { bn::sound_items::mc_2_1_4, "Mc 2 1 4" },
    { bn::sound_items::mc_2_2_1, "Mc 2 2 1" },
    { bn::sound_items::mc_2_2_2, "Mc 2 2 2" },
    { bn::sound_items::mc_2_2_3, "Mc 2 2 3" },
    { bn::sound_items::mc_2_2_4, "Mc 2 2 4" },
    { bn::sound_items::mc_2_3_1, "Mc 2 3 1" },
    { bn::sound_items::mc_2_3_2, "Mc 2 3 2" },
    { bn::sound_items::mc_2_3_3, "Mc 2 3 3" },
    { bn::sound_items::mc_3_1_1, "Mc 3 1 1" },
    { bn::sound_items::mc_3_1_2, "Mc 3 1 2" },
    { bn::sound_items::mc_3_1_3, "Mc 3 1 3" },
    { bn::sound_items::mc_3_1_4, "Mc 3 1 4" },
    { bn::sound_items::mc_test_04, "Mc Test 04" },
    { bn::sound_items::mc_test_05, "Mc Test 05" },
    { bn::sound_items::menu_confirm, "Menu Confirm" },
    { bn::sound_items::menu_focus, "Menu Focus" },
    { bn::sound_items::player_damage, "Player Damage" },
    { bn::sound_items::player_death, "Player Death" },
    { bn::sound_items::player_laser, "Player Laser" },
};
} // namespace audio_viewer_defs

#endif // AUDIO_VIEWER_SCENE_DEFS_H
