#ifndef MODEL_VIEWER_SCENE_DEFS_H
#define MODEL_VIEWER_SCENE_DEFS_H

// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/batch_import_models.py
// Models included: 7

#include "model_viewer_scene.h"

#include "models/asteroid1.h"
#include "models/bush.h"
#include "models/moon_oyster.h"
#include "models/player_ship_01.h"
#include "models/player_ship_02.h"
#include "models/scorpion.h"
#include "models/shot.h"

namespace model_viewer_defs {
inline constexpr int models_count = 7;
inline const model_viewer_scene::model_entry entries[models_count] = {
    { &fr::model_3d_items::asteroid1_full, "Asteroid1" },
    { &fr::model_3d_items::bush_full, "Bush" },
    { &fr::model_3d_items::moon_oyster_full, "Moon Oyster" },
    { &fr::model_3d_items::player_ship_01_full, "Player Ship 01" },
    { &fr::model_3d_items::player_ship_02_full, "Player Ship 02" },
    { &fr::model_3d_items::scorpion_full, "Scorpion" },
    { &fr::model_3d_items::shot_full, "Shot" },
};
} // namespace model_viewer_defs

#endif // MODEL_VIEWER_SCENE_DEFS_H
