#ifndef MUSIC_VIEWER_SCENE_DEFS_H
#define MUSIC_VIEWER_SCENE_DEFS_H

// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate_music_viewer_defs.py
// Music files included: 3

#include "music_viewer_scene.h"
#include "bn_music_item.h"

#include "bn_music_items.h"

namespace music_viewer_defs {
inline constexpr int music_count = 3;
inline const music_viewer_scene::music_entry entries[music_count] = {
    { bn::music_items::gameplay_p1, "Gameplay P1" },
    { bn::music_items::title_v1, "Title V1" },
    { bn::music_items::title_v2, "Title V2" },
};
} // namespace music_viewer_defs

#endif // MUSIC_VIEWER_SCENE_DEFS_H
