#!/usr/bin/env python3
import os
import sys
import glob
import json
from pathlib import Path

# Local import of converter
import wavefront2v3d

"""
Batch converter:
 - Scans ./obj (relative to project root or current working directory) for *.obj
 - For each foo.obj looks for foo.json alongside (metadata) and foo.hpp output path in ./include/generated/ (created if missing)
 - Model name derived from filename stem (non-alnum replaced with underscore)
 - Scale argument: if metadata has engine_scale it overrides; else default 10.0 (same semantics as earlier)
Usage:
    python tools/batch_import_models.py [obj_folder] [out_folder]
Defaults:
    obj_folder = ./obj
    out_folder = ./include/generated
"""

def sanitize_name(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum() or ch == '_':
            out.append(ch)
        else:
            out.append('_')
    return ''.join(out)

def _generate_model_viewer_defs(repo_root: Path, obj_dir: Path, processed_model_names: list[str]) -> None:
    if not processed_model_names:
        print('No models processed; skipping model_viewer_scene_defs.h generation.')
        return

    scenes_dir = repo_root / 'include' / 'scenes'
    scenes_dir.mkdir(parents=True, exist_ok=True)
    defs_path = scenes_dir / 'model_viewer_scene_defs.h'

    processed_model_names.sort()  # deterministic order

    def display_name(name: str) -> str:
        parts = [p for p in name.split('_') if p]
        if not parts:
            return name
        return ' '.join(p.capitalize() for p in parts)

    includes_block = '\n'.join(f'#include "models/{mn}.h"' for mn in processed_model_names)
    entries_lines = [f'    {{ &fr::model_3d_items::{mn}_full, "{display_name(mn)}" }},' for mn in processed_model_names]
    entries_block = '\n'.join(entries_lines)
    count_value = len(processed_model_names)

    header = f'''#ifndef MODEL_VIEWER_SCENE_DEFS_H\n#define MODEL_VIEWER_SCENE_DEFS_H\n\n// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.\n// Generated by tools/batch_import_models.py\n// Models included: {count_value}\n\n#include "model_viewer_scene.h"\n\n{includes_block}\n\nnamespace model_viewer_defs {{\ninline constexpr int models_count = {count_value};\ninline const model_viewer_scene::model_entry entries[models_count] = {{\n{entries_block}\n}};\n}} // namespace model_viewer_defs\n\n#endif // MODEL_VIEWER_SCENE_DEFS_H\n'''

    try:
        existing = defs_path.read_text(encoding='utf-8') if defs_path.exists() else None
    except Exception:
        existing = None

    if existing != header:
        defs_path.write_text(header, encoding='utf-8')
        print(f'Updated {defs_path.relative_to(repo_root)}')
    else:
        print('model_viewer_scene_defs.h already up to date.')


def main(argv):
    # Anchor defaults to repository root (parent of this script's directory)
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    obj_dir = Path(argv[1]) if len(argv) > 1 else repo_root / 'obj'
    out_dir = Path(argv[2]) if len(argv) > 2 else repo_root / 'include' / 'models'
    obj_dir = obj_dir.resolve()
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    objs = sorted(obj_dir.glob('*.obj'))
    if not objs:
        print(f'No OBJ files found in {obj_dir}')
        _generate_model_viewer_defs(repo_root, obj_dir, [])  # ensure header is not stale
        return 0

    converted = 0
    processed_model_names: list[str] = []  # sanitized model identifiers (match generated headers)
    for obj_path in objs:
        stem = obj_path.stem
        modelname = sanitize_name(stem)
        metadata_path = obj_path.with_suffix('.json')
        modelscale = 10.0  # default scale (metadata may override inside converter)
        out_path = out_dir / f'{modelname}.h'
        overwrite = out_path.exists()
        print(f'Converting {obj_path.name} -> {out_path.name}' + (' (overwrite)' if overwrite else ''))
        try:
            wavefront2v3d.convert_wavefront(
                str(obj_path),
                str(out_path),
                modelname,
                modelscale,
                recalcvertexnorms=False,
                metadata_path=str(metadata_path) if metadata_path.exists() else None
            )
            converted += 1
            processed_model_names.append(modelname)
        except Exception as e:
            print(f'ERROR converting {obj_path}: {e}')
    print(f'Done. Converted {converted}/{len(objs)} OBJ files.')

    _generate_model_viewer_defs(repo_root, obj_dir, processed_model_names)
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
