#!/usr/bin/env python3
import os
import sys
from pathlib import Path
from termcolor import colored

def sanitize_name(name: str) -> str:
    """Convert filename to valid C++ identifier."""
    out = []
    for ch in name:
        if ch.isalnum() or ch == '_':
            out.append(ch)
        else:
            out.append('_')
    return ''.join(out)

def display_name(name: str) -> str:
    """Convert snake_case to Title Case."""
    parts = [p for p in name.split('_') if p]
    if not parts:
        return name
    return ' '.join(p.capitalize() for p in parts)

def main(argv=None):
    # Anchor to repository root
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    audio_dir = repo_root / 'audio'
    scenes_dir = repo_root / 'include' / 'scenes'
    
    # Ensure output directory exists
    scenes_dir.mkdir(parents=True, exist_ok=True)
    defs_path = scenes_dir / 'audio_viewer_scene_defs.h'
    
    # Find all .it files
    it_files = sorted(audio_dir.glob('*.it'))
    
    if not it_files:
        print(f'{colored("[audio_viewer]", "light_blue")} No .it files found in {audio_dir}')
        # Create empty header anyway
        processed_names = []
    else:
        processed_names = []
        for it_file in it_files:
            stem = it_file.stem
            sanitized = sanitize_name(stem)
            processed_names.append((sanitized, display_name(stem)))
            print(f'{colored("[audio_viewer]", "light_blue")} Found: {it_file.name} -> {sanitized}')
    
    # Generate header file
    count_value = len(processed_names)
    
    # Use the single bn_music_items.h header instead of individual headers
    includes_block = '#include "bn_music_items.h"'
    
    entries_lines = [f'    {{ bn::music_items::{name}, "{display}" }},' for name, display in processed_names]
    entries_block = '\n'.join(entries_lines) if entries_lines else '    // No entries'
    
    header_content = f'''#ifndef AUDIO_VIEWER_SCENE_DEFS_H
#define AUDIO_VIEWER_SCENE_DEFS_H

// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate_audio_viewer_defs.py
// Music files included: {count_value}

#include "audio_viewer_scene.h"
#include "bn_music_item.h"

{includes_block}

namespace audio_viewer_defs {{
inline constexpr int music_count = {count_value};
inline const audio_viewer_scene::music_entry entries[music_count{" + 1" if count_value == 0 else ""}] = {{
{entries_block}
}};
}} // namespace audio_viewer_defs

#endif // AUDIO_VIEWER_SCENE_DEFS_H
'''
    
    # Check if file needs updating
    try:
        existing = defs_path.read_text(encoding='utf-8') if defs_path.exists() else None
    except Exception:
        existing = None
    
    if existing != header_content:
        defs_path.write_text(header_content, encoding='utf-8')
        print(f'{colored("[audio_viewer]", "light_blue")} Updated {defs_path.relative_to(repo_root)}')
    else:
        print(f'{colored("[audio_viewer]", "light_blue")} audio_viewer_scene_defs.h already up to date.')
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
