#!/usr/bin/env python3
import sys
from pathlib import Path
from termcolor import colored

def sanitize_name(name: str) -> str:
    """Convert filename to valid C++ identifier."""
    out = []
    for ch in name:
        if ch.isalnum() or ch == '_':
            out.append(ch)
        else:
            out.append('_')
    return ''.join(out)

def display_name(name: str) -> str:
    """Convert snake_case to Title Case."""
    parts = [part for part in name.split('_') if part]
    if not parts:
        return name
    return ' '.join(part.capitalize() for part in parts)

def main(argv=None):
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    audio_dir = repo_root / 'audio'
    scenes_dir = repo_root / 'include' / 'scenes'

    scenes_dir.mkdir(parents=True, exist_ok=True)
    defs_path = scenes_dir / 'audio_viewer_scene_defs.h'

    wav_files = sorted(audio_dir.glob('*.wav'))

    if not wav_files:
        print(f'{colored("[audio_viewer]", "cyan")} No .wav files found in {audio_dir}')
        processed_names = []
    else:
        processed_names = []
        for wav_file in wav_files:
            stem = wav_file.stem
            sanitized = sanitize_name(stem)
            processed_names.append((sanitized, display_name(stem)))
            print(f'{colored("[audio_viewer]", "cyan")} Found: {wav_file.name} -> {sanitized}')

    count_value = len(processed_names)
    includes_block = '#include "bn_sound_items.h"'

    entries_lines = [f'    {{ bn::sound_items::{name}, "{display}" }},' for name, display in processed_names]
    entries_block = '\n'.join(entries_lines) if entries_lines else '    // No entries'

    header_content = f'''#ifndef AUDIO_VIEWER_SCENE_DEFS_H
#define AUDIO_VIEWER_SCENE_DEFS_H

// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate_audio_viewer_defs.py
// Sound files included: {count_value}

#include "audio_viewer_scene.h"
#include "bn_sound_item.h"

{includes_block}

namespace audio_viewer_defs {{
inline constexpr int sound_count = {count_value};
inline const audio_viewer_scene::sound_entry entries[sound_count{" + 1" if count_value == 0 else ""}] = {{
{entries_block}
}};
}} // namespace audio_viewer_defs

#endif // AUDIO_VIEWER_SCENE_DEFS_H
'''

    try:
        existing = defs_path.read_text(encoding='utf-8') if defs_path.exists() else None
    except Exception:
        existing = None

    if existing != header_content:
        defs_path.write_text(header_content, encoding='utf-8')
        print(f'{colored("[audio_viewer]", "cyan")} Updated {defs_path.relative_to(repo_root)}')
    else:
        print(f'{colored("[audio_viewer]", "cyan")} audio_viewer_scene_defs.h already up to date.')

    return 0

if __name__ == '__main__':
    sys.exit(main())